language: python
python:
  - "2.7"
  - "3.4"
cache: pip
install:
  - pip install -r requirements.txt
before_install:
  - sudo apt-get install pandoc
script:
  - tox
after-script:
  - bash coverage.sh
