language: python
python:
  - "2.7"
  - "3.4"
cache: pip
before_install:
  - sudo apt-get install pandoc
install:
  - pip install -r requirements.txt
  - pip install tox-travis
script:
  - tox
after-script:
  - bash coverage.sh
